version: "3"
services:
  node:
    image: node:7.2.1
    container_name: node
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    working_dir: "/src"
  nginx:
    image: nginx:1.19.5-alpine
    ports:
      - "80:80"
    volumes:
      - "./src:/usr/share/nginx/html"